### PR TITLE
nasdf: Initialize.

### PR DESCRIPTION
**Pull request by Ambrevar**
@aartaka @aadcg What to you think?

To do:

- [x] Adapt the .asd so that it leverages the submodule system and the test system.

### CODE REVIEW

**Comment by aartaka** [comment]
Good so far (it's a verbatim copy of NASDF, right?), let's see what happens with .asd :)

**Comment by aadcg** [comment]
Nothing to add for now!

**Comment by aartaka** [comment]
The best testing scenario for `ntemplate` is: 
- propagate changes into an existing library (my personal testing ground is `njson` :D),
- see what breaks, 
- fix in `ntemplate`, 
- and propagate to other libraries :P

**Comment by Ambrevar** [comment]
Done!  Instead of njson, I've used https://github.com/atlas-engineer/history-tree/ because I was working on it.

Should be ready to merge.  Thoughts?

**Comment by aadcg** [comment]
Nothing to add. Ok from my side.

**Review by aartaka — APPROVED** [review]

**Comment by Ambrevar** [comment]
Done, thanks!

**Pull request merged**
